export const defaultQuestions: { [key: string]: string[] } = {
  "feedback-questions": [
    "How satisfied are you with our service?",
    "What aspects of our service do you like most?",
    "What specific improvements would you suggest?",
    "How likely are you to recommend us to others?",
    "What was the main reason you chose our service?",
    "How could we enhance your experience with us?",
    "What aspects of our service could be better?",
    "How do our services compare to other providers?",
    "What makes you continue using our services?",
    "What would cause you to switch to a different provider?",
  ],
  "customer-experience-questions": [
    "How would you rate your experience with us?",
    "Was our website easy to navigate?",
    "How satisfied were you with our customer service?",
    "Would you purchase from us again?",
    "What aspects of your experience need improvement?",
    "How smooth was the purchase process?",
    "Did you encounter any problems while shopping with us?",
    "How satisfied are you with your purchase quality?",
    "How helpful was our staff during your visit?",
    "What would make your experience with us better?",
  ],
  "customer-service-questions": [
    "How quickly did our support team respond?",
    "Was your problem completely resolved?",
    "How knowledgeable was our support agent?",
    "What was your support wait time?",
    "Would you recommend our customer service?",
    "How professional was our support team?",
    "Did we fully address your service needs?",
    "What could we do to improve our support?",
    "How satisfied were you with our follow-up?",
    "How clear was our communication?",
  ],
  "product-survey-questions": [
    "Which product features do you use most often?",
    "Why did you select our product?",
    "How frequently do you use our product?",
    "What problems does our product solve for you?",
    "What additional features would you like?",
    "How does our product compare to alternatives?",
    "How intuitive is our product to use?",
    "What aspects of our product need improvement?",
    "How could we enhance our product?",
    "How likely are you to recommend our product?",
  ],
  "user-experience-questions": [
    "How easy is it to use our platform?",
    "Were you able to accomplish your goals?",
    "How would you rate our interface design?",
    "What was your biggest usability challenge?",
    "Which features would improve your experience?",
    "How easy is it to find what you need?",
    "How well does our platform work on mobile?",
    "What key features are we missing?",
    "What frustrates you about our platform?",
    "How likely are you to continue using our platform?",
  ],
  "brand-perception-questions": [
    "What three words describe our brand?",
    "What makes our brand unique?",
    "How much do you trust our brand?",
    "What values do you associate with us?",
    "Would you recommend our brand?",
    "How do you view our brand reputation?",
    "What feelings does our brand evoke?",
    "Is our brand message consistent?",
    "How could our brand improve?",
    "How do we compare to similar brands?",
  ],
  "employee-satisfaction-questions": [
    "How fulfilled are you in your current role?",
    "Do you feel appreciated at work?",
    "Rate your work-life balance",
    "Are you growing professionally here?",
    "Would you recommend working here?",
    "How effective is team collaboration?",
    "Do you have the tools to succeed?",
    "Is feedback helpful and regular?",
    "What would improve your workplace?",
    "Are your career goals supported here?",
  ],
  "education-feedback-questions": [
    "How effective was the teaching?",
    "Did the content keep you engaged?",
    "Were your learning objectives met?",
    "Rate the quality of course materials",
    "What would enhance this course?",
    "Was the learning pace suitable?",
    "How well did the instructor teach?",
    "Were concepts clearly explained?",
    "What could improve the learning experience?",
    "Would you take another course with us?",
  ],
  "healthcare-experience-questions": [
    "Rate your overall care experience",
    "How professional was our medical staff?",
    "How clean were our facilities?",
    "Were your medical concerns addressed?",
    "Would you choose us again?",
    "How easy was scheduling?",
    "Did you feel respected during your visit?",
    "How effective was your treatment?",
    "What would improve our care?",
    "Was your waiting time acceptable?",
  ],
  "event-feedback-questions": [
    "How would you rate this event?",
    "Was the event well-planned?",
    "Rate the event location",
    "Did the event meet your expectations?",
    "Would you attend future events?",
    "How engaging were the speakers?",
    "Was the content valuable?",
    "What would make our events better?",
    "How useful was the information?",
    "Rate the networking opportunities",
  ],
  "market-research-questions": [
    "What drives your purchase decisions?",
    "How often do you buy this product?",
    "Which product features matter most?",
    "How do you evaluate products?",
    "What would make you change brands?",
    "What's your ideal price range?",
    "How important is brand reputation?",
    "What do you prioritize when buying?",
    "How do you find new products?",
    "What influences your final purchase?",
  ],
  "training-evaluation-questions": [
    "Was this training applicable to your work?",
    "How would you rate the trainer?",
    "What new skills did you gain?",
    "Was the training speed appropriate?",
    "Would you recommend this training?",
    "Rate the training facilities",
    "How helpful were the materials?",
    "What would improve this training?",
    "How engaging was the session?",
    "Did the training meet your needs?",
  ],
  "remote-work-survey": [
    "Rate your remote work productivity",
    "What remote work challenges do you face?",
    "How suitable is your home office?",
    "Do you feel connected to the team?",
    "What remote work support do you need?",
    "How effective is team communication?",
    "Do you have adequate remote tools?",
    "What would improve remote work?",
    "Rate your remote work-life balance",
    "How often do you collaborate remotely?",
  ],
  "digital-transformation-survey": [
    "How comfortable are you with digital changes?",
    "Which digital tools benefit you most?",
    "Have processes become more efficient?",
    "What digital training do you need?",
    "How has digitalization affected productivity?",
    "Rate your technology adaptation",
    "What digital hurdles do you face?",
    "How can we help with digital adoption?",
    "Are new systems user-friendly?",
    "How has technology changed your work?",
  ],
  "sustainability-practices": [
    "How important is sustainability to you?",
    "Which green initiatives work best?",
    "Do you participate in recycling?",
    "How can we reduce environmental impact?",
    "What sustainability programs interest you?",
    "How do you support sustainability?",
    "What environmental challenges exist?",
    "How can we be more sustainable?",
    "Is sustainability valued here?",
    "What green resources do you need?",
  ],
  "diversity-inclusion-survey": [
    "Do you feel welcome and included?",
    "Is leadership diverse enough?",
    "Are company policies equitable?",
    "How can we improve inclusion?",
    "Do you see yourself represented?",
    "Rate our workplace inclusivity",
    "What diversity challenges exist?",
    "How can we support all employees?",
    "Are opportunities equally available?",
    "What would make us more inclusive?",
  ],
  "mental-health-wellness": [
    "Rate your current stress level",
    "Do you feel supported at work?",
    "Which wellness programs help most?",
    "How's your work-life balance?",
    "What mental health support do you need?",
    "How do you handle work stress?",
    "What wellness challenges do you face?",
    "How can we support mental health?",
    "Is wellbeing a company priority?",
    "What wellness resources would help?",
  ],
  "innovation-feedback": [
    "How innovative is our workplace?",
    "Are new ideas encouraged here?",
    "What hinders innovation?",
    "How innovative are we versus competitors?",
    "What would boost creativity?",
    "How can we foster innovation?",
    "What blocks creative thinking?",
    "Is calculated risk-taking supported?",
    "What innovation resources do you need?",
    "How could we be more innovative?",
  ],
  "social-media-engagement": [
    "Which social platforms do you prefer?",
    "Rate our social media content",
    "What content interests you most?",
    "What's the ideal posting frequency?",
    "Would you share our content?",
    "How can we boost engagement?",
    "What social media issues exist?",
    "How do you engage with our posts?",
    "What content topics interest you?",
    "How can we improve our social presence?",
  ],
  "customer-loyalty-program": [
    "How valuable are our rewards?",
    "How often do you use rewards?",
    "Which benefits matter most?",
    "Is our loyalty program user-friendly?",
    "What would increase your loyalty?",
    "How can we improve rewards?",
    "What program issues exist?",
    "Preferred way to earn points?",
    "Which rewards interest you most?",
    "What would increase program usage?",
  ],
  "website-usability": [
    "How easy is our website to use?",
    "Rate our website navigation",
    "How's our mobile website?",
    "What website features do you need?",
    "Will you visit again?",
    "What makes our website difficult?",
    "Rate our website speed",
    "Is our website visually appealing?",
    "How easy is checkout?",
    "What content interests you most?",
  ],
  "community-engagement": [
    "How engaged are you with our community?",
    "Which community events interest you?",
    "How can we serve the community better?",
    "Do you feel part of our community?",
    "What local impact do we have?",
    "How can we increase involvement?",
    "What community needs exist?",
    "How do you contribute?",
    "What community issues matter most?",
    "How can we support local growth?",
  ],
  "process-improvement": [
    "Where are the workflow bottlenecks?",
    "How can we improve efficiency?",
    "Which processes need updating?",
    "Are current tools effective?",
    "What needs immediate change?",
    "How can we reduce waste?",
    "What process problems exist?",
    "Your best improvement suggestion?",
    "What resources would help?",
    "How can we optimize workflows?",
  ],
  "mobile-app-experience": [
    "How user-friendly is our app?",
    "Which app features do you use most?",
    "Rate our app's reliability",
    "What app features are needed?",
    "Would you recommend our app?",
    "How can we improve the app?",
    "What app issues do you face?",
    "Rate our app's design",
    "How easy is app navigation?",
    "What app content matters most?",
  ],
  "marketing-campaign": [
    "Where did you see our campaign?",
    "Which message caught your attention?",
    "Was our marketing relevant to you?",
    "Did you take action after seeing our ad?",
    "How can we improve our marketing?",
    "Preferred marketing channels?",
    "What marketing issues exist?",
    "Rate our campaign design",
    "Which offers interest you?",
    "How can we better reach you?",
  ],
  "sales-performance": [
    "Rate our sales process",
    "What helps you close sales?",
    "Which sales tools do you need?",
    "How qualified are the leads?",
    "What prevents sales completion?",
    "How can we improve sales?",
    "What sales obstacles exist?",
    "Rate customer interactions",
    "What sales resources help most?",
    "How can we support sales better?",
  ],
  "customer-support": [
    "Rate your support experience",
    "How quickly was your issue resolved?",
    "Was our support staff helpful?",
    "Did the solution work?",
    "Would you use our support again?",
    "How can we improve support?",
    "What support issues exist?",
    "Rate our support communication",
    "What support tools would help?",
    "How can we serve you better?",
  ],
};

export function getRandomQuestions(
  category: string,
  count: number = 5
): string[] {
  const categoryQuestions = defaultQuestions[category] || [];
  const shuffled = [...categoryQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
