export const allQuestions: { [key: string]: string[] } = {
  "feedback-questions": [
    "How satisfied are you with our product/service?",
    "What aspects of our product/service do you like the most?",
    "What improvements would you suggest for our product/service?",
    "How likely are you to recommend us to others?",
    "What was the main reason you chose our product/service?",
    "How well did our product/service meet your expectations?",
    "What features would you like to see added in the future?",
    "How would you rate the value for money of our product/service?",
    "What was your biggest concern before trying our product/service?",
    "How easy was it to start using our product/service?",
    "What would make you more likely to continue using our product/service?",
    "How does our product compare to alternatives you've tried?",
    "What is the one thing we could do better?",
    "How well do we communicate product updates and changes?",
    "What motivated you to choose our product initially?",
    "How has our product helped solve your problems?",
    "What features do you find most valuable?",
    "How often do you use our product/service?",
    "What would you miss most if you couldn't use our product anymore?",
    "How well does our product integrate with your existing workflow?"
  ],
  "customer-experience-questions": [
    "How would you rate your overall experience with our company?",
    "Was it easy to find what you were looking for on our website?",
    "How satisfied were you with the checkout process?",
    "Did our product/service solve your problem?",
    "How would you describe your interaction with our staff?",
    "What could we have done better to improve your experience?",
    "Would you use our service again? Why or why not?",
    "How does our service compare to alternatives you've used?",
    "What was the most memorable part of your experience with us?",
    "How likely are you to continue using our product/service?",
    "What was your first impression of our company?",
    "How well did we handle any issues or concerns you had?",
    "What made your experience particularly good or bad?",
    "How easy was it to get the help you needed?",
    "Would you recommend our company to others? Why?",
    "What expectations did we exceed or fail to meet?",
    "How could we make your experience more enjoyable?",
    "What was the biggest challenge you faced while using our service?",
    "How well did we communicate throughout your experience?",
    "What would make you choose us again in the future?"
  ],
  "customer-service-questions": [
    "How would you rate the responsiveness of our customer service team?",
    "Was your issue resolved to your satisfaction?",
    "How knowledgeable was the customer service representative?",
    "How long did you wait before receiving assistance?",
    "Did the customer service representative treat you with respect?",
    "How easy was it to get in touch with customer service?",
    "Would you prefer different channels for customer support?",
    "How could we improve our customer service?",
    "Did the representative understand your problem clearly?",
    "Was the solution provided effective for your issue?",
    "How would you rate the professionalism of our support team?",
    "Were you satisfied with the resolution time?",
    "Did you feel valued as a customer during the interaction?",
    "How clear was the communication from our support team?",
    "Would you use our customer service again based on this experience?",
    "What was the best part of your customer service experience?",
    "How well did the support team follow up on your issue?",
    "Was the support available when you needed it?",
    "How could we make our customer service more helpful?",
    "Did you feel your feedback was taken seriously?"
  ],
  "product-survey-questions": [
    "Which features do you use most frequently?",
    "What made you choose our product over competitors?",
    "How often do you use our product?",
    "What problems does our product solve for you?",
    "Are there any features missing that you'd like to see?",
    "How would you rate the product's reliability?",
    "Is the product easy to use? Why or why not?",
    "What is the main benefit you get from using our product?",
    "How well does the product integrate with your existing tools?",
    "Would you be interested in additional product training?",
    "What feature could we add to make the product more valuable?",
    "How has the product improved your workflow?",
    "What's the biggest challenge you face using our product?",
    "How satisfied are you with the product's performance?",
    "What would make you use the product more often?",
    "How well does the product meet your specific needs?",
    "What alternative solutions did you consider?",
    "How likely are you to upgrade to a premium version?",
    "What would make the product easier to use?",
    "How well does the product documentation help you?"
  ],
  "user-experience-questions": [
    "How easy is it to navigate our website/app?",
    "Did you encounter any difficulties while using our platform?",
    "How would you rate the loading speed of our website/app?",
    "Is the information you're looking for easy to find?",
    "How would you rate the visual design of our interface?",
    "Were error messages clear and helpful?",
    "How intuitive was the checkout/signup process?",
    "Did you find our search function helpful?",
    "How would you rate the mobile experience?",
    "What would make our website/app easier to use?",
    "How satisfied are you with the overall layout?",
    "Was the navigation menu easy to understand?",
    "Did you find all the features you were looking for?",
    "How would you improve the user interface?",
    "Was the content well-organized and easy to read?",
    "Did the website/app meet your expectations?",
    "How would you rate the overall user experience?",
    "Were you able to complete your tasks efficiently?",
    "What features would make your experience better?",
    "How does our platform compare to others you've used?"
  ],
  "brand-perception-questions": [
    "What words would you use to describe our brand?",
    "How well do our values align with yours?",
    "What makes our brand stand out from competitors?",
    "How trustworthy do you consider our brand to be?",
    "Would you consider yourself loyal to our brand?",
    "How likely are you to choose our brand in the future?",
    "What associations come to mind when you think of our brand?",
    "How well does our brand communicate its message?",
    "Do you feel our brand understands your needs?",
    "What could we do to improve our brand image?",
    "How does our brand make you feel?",
    "What attracted you to our brand initially?",
    "Does our brand reflect quality and reliability?",
    "How well does our brand represent its values?",
    "Would you recommend our brand to others?",
    "What would make you more loyal to our brand?",
    "How consistent is our brand across different channels?",
    "What do you think our brand stands for?",
    "How has your perception of our brand changed over time?",
    "What would make our brand more appealing to you?"
  ],
  "employee-satisfaction-questions": [
    "How satisfied are you with your current role?",
    "Do you feel valued as an employee?",
    "How would you rate the work-life balance in your position?",
    "Are you satisfied with the opportunities for career growth?",
    "How well does your manager support your professional development?",
    "Do you have the resources needed to do your job effectively?",
    "How would you rate internal communication in the company?",
    "Do you feel your opinions are heard and valued?",
    "How satisfied are you with the company culture?",
    "Would you recommend our company as a great place to work?",
    "How well does the company support your wellbeing?",
    "Are you satisfied with the recognition you receive?",
    "How would you rate collaboration within your team?",
    "Do you feel aligned with the company's mission and values?",
    "How satisfied are you with your compensation package?",
    "Do you see yourself growing with the company long-term?",
    "How would you rate the quality of leadership?",
    "Are you satisfied with the workplace flexibility?",
    "Do you feel challenged and engaged in your role?",
    "How would you rate the overall employee experience?"
  ],
  "education-feedback-questions": [
    "How would you rate the overall quality of instruction?",
    "Was the course content relevant and engaging?",
    "How effective were the teaching methods used?",
    "Did the course meet your learning objectives?",
    "How would you rate the quality of course materials?",
    "Was the feedback on assignments helpful?",
    "How well-organized was the course structure?",
    "Did you receive adequate support when needed?",
    "How would you rate the learning environment?",
    "Were the assessment methods fair and appropriate?",
    "How engaging were the class discussions?",
    "Did the course challenge you intellectually?",
    "How effective was the use of technology in learning?",
    "Was the workload manageable?",
    "How would you rate the instructor's knowledge?",
    "Did the course prepare you for practical application?",
    "How would you rate peer interaction opportunities?",
    "Was the pace of instruction appropriate?",
    "Did you receive clear course expectations?",
    "How would you improve this course?"
  ],
  "healthcare-experience-questions": [
    "How satisfied were you with your overall care experience?",
    "Was the medical staff professional and courteous?",
    "How would you rate the cleanliness of our facility?",
    "Did the healthcare provider explain things clearly?",
    "How long did you wait before being seen?",
    "Were your questions answered thoroughly?",
    "How would you rate the quality of care received?",
    "Was the staff responsive to your needs?",
    "How easy was it to schedule an appointment?",
    "Would you recommend our facility to others?",
    "How would you rate the follow-up care?",
    "Was your privacy respected during your visit?",
    "How satisfied were you with the treatment plan?",
    "Did you feel involved in decisions about your care?",
    "How would you rate the communication from staff?",
    "Was the billing process clear and accurate?",
    "Did you feel comfortable during your visit?",
    "How would you rate the coordination of your care?",
    "Were your concerns addressed adequately?",
    "How could we improve your healthcare experience?"
  ],
  "event-feedback-questions": [
    "How satisfied were you with the overall event?",
    "Was the event well-organized?",
    "How would you rate the venue and facilities?",
    "Was the event content relevant and engaging?",
    "How satisfied were you with the speakers/presenters?",
    "Did the event meet your expectations?",
    "How would you rate the networking opportunities?",
    "Was the event length appropriate?",
    "How would you rate the registration process?",
    "Would you attend this event again?",
    "How satisfied were you with the catering/refreshments?",
    "Was the event schedule well-planned?",
    "How would you rate the event staff?",
    "Did you find the event valuable?",
    "How was the audio-visual quality?",
    "Were the sessions interactive enough?",
    "How would you rate the event communication?",
    "Was the event worth your time and money?",
    "What was the most valuable part of the event?",
    "How could we improve future events?"
  ],
  "market-research-questions": [
    "What factors influence your purchasing decisions?",
    "How often do you purchase products in this category?",
    "What features are most important to you?",
    "How much would you be willing to pay for this product?",
    "Which brands do you currently use?",
    "What would make you switch brands?",
    "How do you research products before buying?",
    "Where do you typically shop for these products?",
    "What problems are you trying to solve?",
    "How important is brand reputation to you?",
    "What trends have you noticed in this market?",
    "How do you prefer to receive product information?",
    "What makes a product stand out to you?",
    "How do you evaluate product quality?",
    "What role does price play in your decisions?",
    "How do you use similar products currently?",
    "What would make you recommend a product?",
    "How do you feel about current market options?",
    "What improvements would you like to see?",
    "How do you define value in this category?"
  ],
  "training-evaluation-questions": [
    "How relevant was the training content to your role?",
    "Were the learning objectives clearly defined?",
    "How would you rate the trainer's effectiveness?",
    "Was the training material well-organized?",
    "Did the training meet your expectations?",
    "How confident do you feel applying what you learned?",
    "Was the training pace appropriate?",
    "How engaging were the training activities?",
    "Would you recommend this training to colleagues?",
    "How would you rate the practical exercises?",
    "Was the training time well-utilized?",
    "How would you rate the training materials?",
    "Did the training address your learning needs?",
    "How effective were the teaching methods?",
    "Was the content easy to understand?",
    "How useful were the examples provided?",
    "Did you receive adequate practice opportunities?",
    "How would you rate the overall training quality?",
    "What skills did you gain from this training?",
    "How could the training be improved?"
  ]
};

export function getRandomQuestions(category: string, count: number = 10): string[] {
  const categoryQuestions = allQuestions[category] || [];
  const shuffled = [...categoryQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export const questions = Object.fromEntries(
  Object.entries(allQuestions).map(([key, value]) => [key, getRandomQuestions(key)])
);